(() => {
'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fighters=[
 {name:'REX',style:'BOXING / KICKBOXING',power:91,speed:72,defense:88,skin:'#b86e4d',gear:'#16171a',tone:'#92352b',accent:'#e1332f',portrait:'ChatGPT%20Image%20Aug%2031%2C%202026%2C%2012_45_44%20AM.png'},
 {name:'KAI',style:'MUAY THAI',power:78,speed:94,defense:72,skin:'#b8744f',gear:'#6e1718',tone:'#9a5526',accent:'#e8ad42'},
 {name:'ARJUN',style:'MIXED MARTIAL ARTS',power:84,speed:84,defense:82,skin:'#845238',gear:'#183c3d',tone:'#29645e',accent:'#41a897'}
];
const attacks={
 j:{name:'Jab',wind:5,active:5,recovery:11,damage:6,range:80,cost:7,type:'high'},
 k:{name:'Heavy Cross',wind:14,active:6,recovery:22,damage:14,range:92,cost:18,type:'high',heavy:true},
 u:{name:'Low Kick',wind:9,active:6,recovery:16,damage:8,range:105,cost:11,type:'low'},
 i:{name:'Roundhouse',wind:17,active:7,recovery:25,damage:17,range:130,cost:23,type:'high',heavy:true,knock:true},
 o:{name:'Beast Rush',wind:20,active:10,recovery:31,damage:25,range:145,cost:10,special:50,type:'mid',heavy:true,knock:true},
 throw:{name:'Throw',wind:10,active:5,recovery:25,damage:16,range:52,cost:20,type:'throw',knock:true},
 jump:{name:'Flying Strike',wind:5,active:10,recovery:20,damage:12,range:105,cost:14,type:'mid',heavy:true}
};
let selected=0,mode='menu',difficulty='Normal',last=0,paused=false,round=1,time=90,roundClock=0,roundWins=[0,0],shake=0,zoom=1,slow=1,hitFreeze=0,particles=[],keys={},lastTap={},sound=true,audio=null,announceTimer=0,aiClock=0;

class FighterAnimation{
 constructor(owner){this.owner=owner;this.state='idle';this.previous='idle';this.time=0;this.blend=1;this.recoil=0;this.step=0}
 set(state){state=({'walk':'walk-forward','back':'walk-backward','jab':'light-punch','heavy-cross':'heavy-punch','low-kick':'light-kick','roundhouse':'heavy-kick','flying-strike':'jump','beast-rush':'special'}[state]||state);if(state===this.state)return;this.previous=this.state;this.state=state;this.time=0;this.blend=0}
 update(dt){this.time+=dt;this.blend=Math.min(1,this.blend+dt*11);this.recoil*=Math.pow(.015,dt);if(['walk-forward','walk-backward','dash'].includes(this.state))this.step+=dt*(this.state==='dash'?14:8);else this.step+=(0-this.step)*Math.min(1,dt*5)}
 attackPhase(){let f=this.owner,a=this.owner.attack;if(!a)return 0;return f.frame<a.wind?f.frame/a.wind:f.frame<a.wind+a.active?1+(f.frame-a.wind)/a.active:2+(f.frame-a.wind-a.active)/a.recovery}
}
function fit(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)} addEventListener('resize',fit);fit();
function cards(){ $('#fighterCards').innerHTML=fighters.map((f,i)=>`<article class="fighter-card ${i===selected?'selected':''}" data-i="${i}"><div class="portrait ${f.portrait?'portrait-art':''}" style="--skin:${f.skin};--gear:${f.gear};--tone:${f.tone}${f.portrait?`;--portrait:url('${f.portrait}')`:''}"><i class="head"></i><i class="body"></i></div><div class="fighter-data"><span>${f.style}</span><h3>${f.name}</h3>${['POWER','SPEED','DEFENSE'].map(x=>`<div class="stat"><span>${x}</span><i style="--v:${f[x.toLowerCase()]}%"></i></div>`).join('')}</div></article>`).join(''); $$('.fighter-card').forEach(c=>c.onclick=()=>{selected=+c.dataset.i;cards();tone(180,.05)}) }cards();
function screen(id){$$('.screen').forEach(x=>x.classList.remove('active')); if(id)$('#'+id).classList.add('active');mode=id||'fight'}
$$('.back').forEach(b=>b.onclick=()=>screen('menu'));$('#selectBtn').onclick=()=>screen('select');$('#howBtn').onclick=()=>screen('how');$('#playBtn').onclick=()=>{screen('select')};$('#beginBtn').onclick=()=>{difficulty=$('#difficulty').value;startMatch()};
function mainMenu(){paused=false;$('#pause').classList.add('hidden');$('#gameover').classList.add('hidden');$('#hud').classList.add('hidden');$('#touch').classList.add('hidden');screen('menu')}
$$('.main-menu').forEach(b=>b.onclick=mainMenu);$('#pauseBtn').onclick=()=>togglePause(true);$('#resumeBtn').onclick=()=>togglePause(false);$('#restartBtn').onclick=startMatch;$('#againBtn').onclick=startMatch;
$$('.sound-btn').forEach(b=>b.onclick=()=>{sound=!sound;$$('.sound-btn').forEach(x=>x.textContent=(sound?'◖ SOUND ON':'◖ SOUND OFF'))});
function togglePause(v){if(mode!=='fight')return;paused=v;$('#pause').classList.toggle('hidden',!v)}
function tone(freq,dur=.08,type='sine',vol=.12){if(!sound)return; audio ||= new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(40,freq*.35),audio.currentTime+dur);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
class Fighter{
 constructor(data,side){this.data=data;this.side=side;this.animation=new FighterAnimation(this);this.reset()}
 reset(){this.x=this.side?innerWidth*.73:innerWidth*.27;this.y=0;this.vx=0;this.vy=0;this.health=100;this.stamina=100;this.meter=0;this.state='idle';this.frame=0;this.attack=null;this.hit=false;this.facing=this.side?-1:1;this.combo=[];this.comboTime=0;this.stun=0;this.knock=0;this.flash=0;this.guardTime=0;this.victory=false;this.animation.set('idle')}
 act(key){if(this.stun||this.knock||this.attack||this.state==='jump')return; if(key==='o'&&this.meter<50)return;let a=attacks[key];if(!a)return;if(this.stamina<a.cost)return;this.stamina-=a.cost;if(a.special)this.meter-=a.special;this.attack={...a,key};this.frame=0;this.hit=false;this.state='attack';this.combo.push(key);this.combo=this.combo.slice(-3);this.comboTime=55;tone(a.heavy?105:170,.08,'sawtooth',.06)}
 update(input,foe){this.facing=foe.x>this.x?1:-1;this.flash=Math.max(0,this.flash-1);this.guardTime=Math.max(0,this.guardTime-1);if(this.comboTime>0)this.comboTime--;else this.combo=[];
  if(this.victory){this.state='victory';this.animation.set('victory');this.animation.update(1/60);return}
  if(this.knock){this.knock--;this.state=this.knock>25?'knockdown':'recovery';this.animation.set(this.state);this.animation.update(1/60);return}if(this.stun){this.stun--;this.state='hit';this.animation.set('hit');this.animation.update(1/60);return}
  if(this.attack){this.frame++;let a=this.attack;if(this.frame>=a.wind&&this.frame<a.wind+a.active&&!this.hit&&Math.abs(foe.x-this.x)<a.range+(this.state==='jump'?20:0)){this.hit=true;hit(this,foe,a)}if(this.frame>=a.wind+a.active+a.recovery){this.attack=null;this.state='idle'}this.animation.set(this.attack?(this.attack.key==='o'?'special':this.attack.name.toLowerCase().replaceAll(' ','-')):'idle');this.animation.update(1/60);return}
  if(this.state==='jump'){this.vy+=.8;this.y+=this.vy;if(input.attack)this.act('jump');if(this.y>=0){this.y=0;this.vy=0;this.state='idle';dust(this.x,ground(),8)}this.x+=this.vx;this.animation.set('jump');this.animation.update(1/60);return}
  const guarding=input.l, crouch=input.s; if(guarding){this.state=crouch?'crouchguard':'guard';this.vx*=.72;this.guardTime=Math.min(10,this.guardTime+2)}else if(crouch){this.state='crouch';this.vx*=.65}else{let dir=(input.d?1:0)-(input.a?1:0);let speed=this.stamina<20?2.3:3.4;if(input.dash&&this.stamina>=12){this.vx=dir*10;this.stamina-=12;this.state='dash'}else{this.vx+=(dir*speed-this.vx)*.24;this.state=Math.abs(this.vx)>.4?(this.vx*this.facing>0?'walk':'back'):'idle'}if(input.w){this.state='jump';this.vy=-13;this.vx+=dir*2;tone(100,.05)}if(input.attack)this.act(input.attack)}
  this.x+=this.vx;this.x=Math.max(65,Math.min(innerWidth-65,this.x));this.stamina=Math.min(100,this.stamina+(.23*(this.state==='idle'?1.5:1)));this.meter=Math.min(100,this.meter+.018);this.animation.set(this.attack?(this.attack.key==='o'?'special':this.attack.name.toLowerCase().replaceAll(' ','-')):this.state);this.animation.update(1/60)}
}
let player,cpu;
function hit(at,def,a){let blocking=(def.state==='guard'&&a.type!=='low')||(def.state==='crouchguard'&&a.type!=='high');if(a.type==='throw')blocking=false;let counter=!!def.attack&&def.frame<def.attack.wind;let critical=Math.random()<.08;let dmg=a.damage*(counter?1.3:1)*(critical?1.35:1);hitFreeze=a.heavy?7:4;def.animation.recoil=a.heavy?1:.55;if(blocking){dmg*=.18;def.stamina-=a.damage*1.25;def.stun=5;tone(320,.07,'square');spark(def.x,ground()+def.y-135,'#d7d1bf',8);if(def.stamina<=0){def.stamina=0;def.stun=25;dmg*=2.5}}else{def.health=Math.max(0,def.health-dmg);def.stun=a.heavy?18:10;def.vx=at.facing*(a.heavy?11:4);at.meter=Math.min(100,at.meter+dmg*1.2);def.meter=Math.min(100,def.meter+dmg*.7);shake=a.heavy?16:6;slow=a.heavy?.38:.75;setTimeout(()=>slow=1,a.heavy?100:40);tone(a.heavy?55:90,a.heavy?.18:.09,'sawtooth',.18);spark(def.x+at.facing*15,ground()+def.y-145,critical?'#fff1a6':'#ef493e',a.heavy?24:12);dust(def.x,ground(),a.heavy?12:6);if(a.knock||def.health<=0){def.knock=def.health<=0?150:48;def.stun=0}if(at.side===0){let n=at.combo.length;$('#combo').innerHTML=n>1?`${n} HIT <small>COMBO</small>`:''}if(counter)flashText('COUNTER');if(critical)flashText('CRITICAL')}
 if(def.health<=0)endRound(at)}
function spark(x,y,color,n){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*12,vy:(Math.random()-.7)*10,life:25+Math.random()*15,color,size:2+Math.random()*5})}
function dust(x,y,n){for(let i=0;i<n;i++)particles.push({x:x+(Math.random()-.5)*45,y:y-Math.random()*8,vx:(Math.random()-.5)*3,vy:-Math.random()*2,life:30+Math.random()*25,color:'#a8a098',size:7+Math.random()*15,dust:true})}
function flashText(t){$('#combo').innerHTML=t}
function ground(){return innerHeight*.82}
function startMatch(){screen(null);$('#pause,#gameover').addClass?.('hidden');$('#pause').addClass?.('hidden');$('#gameover').classList.add('hidden');$('#hud').classList.remove('hidden');if(matchMedia('(pointer:coarse)').matches)$('#touch').classList.remove('hidden');roundWins=[0,0];round=1;player=new Fighter(fighters[selected],0);let ci=(selected+1+Math.floor(Math.random()*2))%3;cpu=new Fighter(fighters[ci],1);$('#pName').textContent=player.data.name;$('#cName').textContent=cpu.data.name;beginRound()}
function beginRound(){time=90;roundClock=0;player.reset();cpu.reset();paused=false;announce(round===3?'FINAL ROUND':`ROUND ${round}`,800,()=>announce('FIGHT',650));tone(440,.3,'square',.08)}
function announce(t,ms=700,cb){$('#announcement').textContent=t;announceTimer=ms;setTimeout(()=>{if($('#announcement').textContent===t)$('#announcement').textContent='';cb&&cb()},ms)}
function endRound(winner){if(roundClock<0)return;roundClock=-999;let wi=winner.side;roundWins[wi]++;winner.victory=true;winner.animation.set('victory');announce('KO',1300,()=>{if(roundWins[wi]>=2){$('#winner').textContent=winner.data.name+' WINS';$('#score').textContent=`ROUNDS ${roundWins[wi]} — ${roundWins[1-wi]}`;$('#gameover').classList.remove('hidden');tone(48,.8,'sawtooth',.2)}else{round++;beginRound()}});slow=.16;zoom=1.1;shake=20;setTimeout(()=>{slow=1;zoom=1},850)}
function aiInput(){let d=Math.abs(player.x-cpu.x),out={};let cfg=difficulty==='Easy'?{react:24,block:.13,attack:.42}:difficulty==='Hard'?{react:7,block:.42,attack:.76}:{react:14,block:.27,attack:.59};aiClock--;if(aiClock<=0){aiClock=cfg.react+Math.random()*cfg.react;let r=Math.random();if(player.attack&&r<cfg.block){cpu.aiGuard=18+Math.random()*18}else if(d>145)cpu.aiMove='a';else if(d<68)cpu.aiMove=Math.random()<.5?'d':null;else cpu.aiMove=null;if(d<150&&Math.random()<cfg.attack){let choices=['j','u','k','i'];if(cpu.meter>=50&&Math.random()<.22)choices.push('o');let last=cpu.combo.at(-1),filtered=choices.filter(x=>x!==last);cpu.aiAttack=filtered[Math.floor(Math.random()*filtered.length)]}}
 if(cpu.aiGuard>0){cpu.aiGuard--;out.l=true;out.s=player.attack?.type==='low'}else{out[cpu.aiMove]=true;if(cpu.aiAttack){out.attack=cpu.aiAttack;cpu.aiAttack=null}}return out}
function update(dt){if(mode!=='fight'||paused||roundClock<0)return;if(hitFreeze>0){hitFreeze--;return}roundClock+=dt;if(roundClock<1.5)return;time=Math.max(0,time-dt);if(time===0){endRound(player.health>=cpu.health?player:cpu);return}let inp={a:keys.a,d:keys.d,w:keys.w,s:keys.s,l:keys.l,dash:keys.dash,attack:keys.attack};keys.attack=null;keys.dash=false;player.update(inp,cpu);cpu.update(aiInput(),player);if(Math.abs(player.x-cpu.x)<72){let push=(72-Math.abs(player.x-cpu.x))*.08;player.x-=player.facing*push;cpu.x+=player.facing*push}particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=p.dust?.05:.4;p.life--});particles=particles.filter(p=>p.life>0).slice(-160);updateHud()}
function updateHud(){for(const [id,v] of [['pHealth',player.health],['pStamina',player.stamina],['pSpecial',player.meter],['cHealth',cpu.health],['cStamina',cpu.stamina],['cSpecial',cpu.meter]])$('#'+id).style.width=Math.max(0,v)+'%';$('#timer').textContent=Math.ceil(time);$('#roundNo').textContent=round;$('#roundPips').textContent=`${'◆'.repeat(roundWins[0])}${'◇'.repeat(2-roundWins[0])}  ${'◆'.repeat(roundWins[1])}${'◇'.repeat(2-roundWins[1])}`}
function drawArena(t){let w=innerWidth,h=innerHeight,g=ground(),pulse=.5+.5*Math.sin(t*.0013);let grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#030405');grad.addColorStop(.54,'#24201f');grad.addColorStop(1,'#070708');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(Math.sin(t*.00018)*12,0);ctx.fillStyle='#121315';for(let y=25;y<g-130;y+=64)for(let x=(y/64%2)*48-80;x<w+100;x+=96){ctx.fillRect(x,y,94,62);ctx.strokeStyle='#242426';ctx.strokeRect(x,y,94,62)}ctx.restore();for(let i=0;i<4;i++){let x=w*(.14+i*.25)+Math.sin(t*.0007+i)*18,beam=ctx.createLinearGradient(x,0,x,g);beam.addColorStop(0,`rgba(255,225,190,${.1+pulse*.04})`);beam.addColorStop(1,'transparent');ctx.fillStyle=beam;ctx.beginPath();ctx.moveTo(x-22,0);ctx.lineTo(x+22,0);ctx.lineTo(x+180,g);ctx.lineTo(x-180,g);ctx.fill();ctx.fillStyle='#f0d3b0';ctx.globalAlpha=.45;ctx.fillRect(x-25,0,50,5);ctx.globalAlpha=1}for(let i=0;i<8;i++){let x=(i*233+t*.012)% (w+300)-150,y=90+(i%4)*82,r=95+(i%3)*35;let fog=ctx.createRadialGradient(x,y,0,x,y,r);fog.addColorStop(0,'#c4b7aa0b');fog.addColorStop(1,'transparent');ctx.fillStyle=fog;ctx.fillRect(x-r,y-r,r*2,r*2)}ctx.fillStyle='#090909';for(let i=0;i<28;i++){let x=i*w/27+Math.sin(t*.001+i*2)*7,y=g-118-(i%4)*9;ctx.beginPath();ctx.arc(x,y,14+(i%3)*3,0,7);ctx.fill();ctx.fillRect(x-16,y+8,32,74);if(i%5===0){ctx.strokeStyle='#171313';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(x,y+25);ctx.lineTo(x+Math.sin(t*.004+i)*18,y-5);ctx.stroke()}}ctx.strokeStyle='#5b5550';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(0,g-72);ctx.lineTo(w,g-72);ctx.stroke();ctx.lineWidth=1;ctx.strokeStyle='#55505a55';for(let x=-30;x<w;x+=48){ctx.beginPath();ctx.moveTo(x,g-72);ctx.lineTo(x+25,g);ctx.stroke()}let floor=ctx.createLinearGradient(0,g-75,0,h);floor.addColorStop(0,'#3a3532');floor.addColorStop(.2,'#171616');floor.addColorStop(1,'#050505');ctx.fillStyle=floor;ctx.fillRect(0,g-75,w,h-g+75);ctx.strokeStyle='#ffffff0c';for(let x=-100;x<w+100;x+=135){ctx.beginPath();ctx.moveTo(w/2+(x-w/2)*.5,g-75);ctx.lineTo(x,h);ctx.stroke()}ctx.fillStyle='#d0b39812';ctx.fillRect(0,g-2,w,3)}
function capsule(a,b,width,color){ctx.strokeStyle=color;ctx.lineWidth=width;ctx.lineCap='round';ctx.beginPath();ctx.moveTo(a[0],a[1]);ctx.lineTo(b[0],b[1]);ctx.stroke()}
function drawSimpleFighter(f){let x=f.x,y=ground()+f.y,face=f.facing,d=f.data;ctx.save();ctx.translate(x,y);ctx.scale(face,1);if(f.knock>25){ctx.rotate(-1.35);ctx.translate(0,-30)}let bob=f.state==='idle'?Math.sin(performance.now()*.007)*3:0,crouch=f.state.includes('crouch')?38:0;ctx.translate(0,bob+crouch);let attacking=f.attack,prog=attacking?f.frame/(attacking.wind+attacking.active+attacking.recovery):0;let punch=attacking&&['j','k','o'].includes(attacking.key)?Math.sin(Math.min(1,prog*2.2)*Math.PI)*55:0,kick=attacking&&['u','i','jump'].includes(attacking.key)?Math.sin(Math.min(1,prog*2)*Math.PI):0,guard=f.state.includes('guard');ctx.strokeStyle=d.skin;ctx.lineCap='round';ctx.lineWidth=20;ctx.beginPath();ctx.moveTo(-24,-98);ctx.lineTo(-29+kick*32,-45);ctx.lineTo(-36-kick*52,0);ctx.stroke();ctx.beginPath();ctx.moveTo(22,-98);ctx.lineTo(30+kick*70,-58-kick*40);ctx.lineTo(35+kick*110,-12-kick*60);ctx.stroke();ctx.fillStyle='#17191b';ctx.fillRect(-47,-96,91,25);ctx.strokeStyle=d.skin;ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(-38,-172);ctx.lineTo(-55,-125);ctx.lineTo(guard?8:-42,-92);ctx.stroke();ctx.beginPath();ctx.moveTo(35,-173);ctx.lineTo(guard?18:48+punch,-132-(punch*.3));ctx.lineTo(guard?5:54+punch,-107-(punch*.25));ctx.stroke();ctx.fillStyle=d.accent;ctx.beginPath();ctx.roundRect(guard?-3:43+punch,-120-(punch*.25),25,20,7);ctx.fill();ctx.fillStyle=d.gear;ctx.beginPath();ctx.moveTo(-42,-178);ctx.quadraticCurveTo(0,-205,42,-178);ctx.lineTo(34,-90);ctx.lineTo(-34,-90);ctx.closePath();ctx.fill();ctx.fillStyle=d.skin;ctx.beginPath();ctx.ellipse(0,-215,31,39,0,0,7);ctx.fill();ctx.fillStyle='#171513';ctx.beginPath();ctx.arc(0,-231,31,Math.PI,0);ctx.fill();ctx.restore()}

function drawRex(f,t){let x=f.x,y=ground()+f.y,A=f.animation,state=A.state,phase=A.attackPhase(),breath=Math.sin(t*.004)*2,step=Math.sin(A.step),crouch=state.includes('crouch')?35:0;let hip=[0,-91+crouch],chest=[-3,-166+crouch+breath],head=[3,-222+crouch+breath],rearFoot=[-29-step*13,0],frontFoot=[38+step*13,0],rearKnee=[-28+step*8,-49+crouch*.35],frontKnee=[28-step*8,-50+crouch*.35],rearElbow=[-49,-145+crouch],rearHand=[-22,-125+crouch],frontElbow=[42,-143+crouch],frontHand=[52,-174+crouch];let guard=state.includes('guard');if(guard){rearHand=[-8,-191+crouch];frontHand=[28,-198+crouch];rearElbow=[-40,-165+crouch];frontElbow=[45,-169+crouch]}
 let strike=Math.sin(Math.min(1,phase<1?phase:phase<2?1:(3-phase))*Math.PI/2);if(f.attack){if(['j','k'].includes(f.attack.key)){frontHand=[48+strike*(f.attack.key==='k'?112:86),-176+strike*15];frontElbow=[42+strike*54,-151+strike*2];chest[0]-=strike*8}else if(f.attack.key==='o'){frontHand=[55+strike*145,-151];frontElbow=[45+strike*82,-145];rearHand=[10+strike*95,-177];chest[0]-=strike*15}else if(['u','i','jump'].includes(f.attack.key)){frontFoot=[45+strike*(f.attack.key==='i'?135:103),-strike*(f.attack.key==='i'?106:47)];frontKnee=[40+strike*62,-52-strike*45]}}
 if(state==='hit'){chest[0]-=18*A.recoil;head[0]-=30*A.recoil;frontHand[0]-=18*A.recoil}if(state==='knockdown'){ctx.save();ctx.translate(x,y);ctx.scale(f.facing,1);ctx.rotate(-1.35);ctx.translate(10,-22);x=0;y=0}else{ctx.save();ctx.translate(x,y);ctx.scale(f.facing,1)}if(state==='recovery'){crouch=45;ctx.rotate(-.18)}if(state==='victory'){rearHand=[-35,-260];frontHand=[38,-266];rearElbow=[-50,-205];frontElbow=[50,-208];head[1]-=5}
 ctx.save();ctx.scale(1,0.32);ctx.fillStyle='#0009';ctx.filter='blur(8px)';ctx.beginPath();ctx.ellipse(0,13,65,25,0,0,7);ctx.fill();ctx.restore();let skin=ctx.createLinearGradient(-45,0,55,0);skin.addColorStop(0,'#6e3428');skin.addColorStop(.45,'#cf805d');skin.addColorStop(.75,'#a9573f');skin.addColorStop(1,'#54271f');capsule(hip,rearKnee,24,skin);capsule(rearKnee,rearFoot,19,skin);capsule(hip,frontKnee,26,skin);capsule(frontKnee,frontFoot,20,skin);ctx.strokeStyle='#131317';ctx.lineWidth=19;ctx.beginPath();ctx.moveTo(rearFoot[0]-9,rearFoot[1]);ctx.lineTo(rearFoot[0]+13,rearFoot[1]);ctx.moveTo(frontFoot[0]-8,frontFoot[1]);ctx.lineTo(frontFoot[0]+18,frontFoot[1]);ctx.stroke();ctx.fillStyle='#151519';ctx.beginPath();ctx.moveTo(-42,-108+crouch);ctx.lineTo(42,-108+crouch);ctx.lineTo(35,-64+crouch*.6);ctx.lineTo(5,-72+crouch*.6);ctx.lineTo(-3,-61+crouch*.6);ctx.lineTo(-38,-67+crouch*.6);ctx.closePath();ctx.fill();ctx.strokeStyle='#d1262e';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(-34,-101+crouch);ctx.lineTo(-8,-73+crouch*.6);ctx.moveTo(34,-101+crouch);ctx.lineTo(10,-73+crouch*.6);ctx.stroke();capsule(chest,rearElbow,27,skin);capsule(rearElbow,rearHand,20,skin);capsule(chest,frontElbow,29,skin);capsule(frontElbow,frontHand,21,skin);ctx.fillStyle=skin;ctx.beginPath();ctx.moveTo(-39,-181+crouch);ctx.quadraticCurveTo(-55,-156+crouch,-36,-112+crouch);ctx.quadraticCurveTo(0,-92+crouch,38,-113+crouch);ctx.quadraticCurveTo(53,-157+crouch,36,-183+crouch);ctx.quadraticCurveTo(0,-198+crouch,-39,-181+crouch);ctx.fill();ctx.strokeStyle='#632d26';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(0,-181+crouch);ctx.lineTo(0,-119+crouch);ctx.moveTo(-24,-151+crouch);ctx.quadraticCurveTo(0,-140+crouch,24,-151+crouch);ctx.stroke();ctx.strokeStyle='#25242a';ctx.lineWidth=4;for(let i=0;i<5;i++){ctx.beginPath();ctx.moveTo(-34+i*3,-180+i*5+crouch);ctx.lineTo(-18+i*2,-148+i*3+crouch);ctx.stroke()}ctx.fillStyle=skin;ctx.beginPath();ctx.ellipse(head[0],head[1],29,36,-.05,0,7);ctx.fill();ctx.fillStyle='#171315';ctx.beginPath();ctx.arc(head[0]-2,head[1]-14,29,Math.PI,6.3);ctx.lineTo(head[0]+21,head[1]-4);ctx.quadraticCurveTo(head[0],head[1]-18,head[0]-25,head[1]-2);ctx.fill();ctx.fillStyle='#211313';ctx.fillRect(head[0]+10,head[1]-3,9,3);ctx.fillRect(head[0]-18,head[1]-3,9,3);ctx.strokeStyle='#45221f';ctx.beginPath();ctx.moveTo(head[0]-9,head[1]+17);ctx.quadraticCurveTo(head[0],head[1]+23,head[0]+11,head[1]+16);ctx.stroke();for(let hand of [rearHand,frontHand]){ctx.fillStyle='#17171b';ctx.beginPath();ctx.roundRect(hand[0]-13,hand[1]-11,27,23,7);ctx.fill();ctx.strokeStyle='#d62431';ctx.lineWidth=4;ctx.strokeRect(hand[0]-10,hand[1]-8,20,16)}if(f.attack?.key==='o'&&strike>.35){ctx.globalCompositeOperation='screen';for(let i=0;i<4;i++){ctx.strokeStyle=`rgba(255,${45+i*30},35,${.65-i*.1})`;ctx.lineWidth=12-i*2;ctx.beginPath();ctx.moveTo(frontHand[0]-20-i*14,frontHand[1]+i*7);ctx.quadraticCurveTo(45,-125,8-i*25,-116);ctx.stroke()}ctx.globalCompositeOperation='source-over'}ctx.restore()}
function render(t){let w=innerWidth,h=innerHeight;ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.translate(w/2,h/2);ctx.scale(zoom,zoom);ctx.translate(-w/2,-h/2);drawArena(t);if(player){player.data.name==='REX'?drawRex(player,t):drawSimpleFighter(player);cpu.data.name==='REX'?drawRex(cpu,t):drawSimpleFighter(cpu)}particles.forEach(p=>{ctx.globalAlpha=Math.min(1,p.life/25)*(p.dust?.28:1);ctx.fillStyle=p.color;if(p.dust){ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,7);ctx.fill()}else ctx.fillRect(p.x,p.y,p.size,p.size)});ctx.restore();ctx.globalAlpha=1;shake*=.82}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt*slow);render(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(k==='escape')togglePause(!paused);if(['a','d','w','s','l'].includes(k)){if(!e.repeat&&['a','d'].includes(k)&&performance.now()-(lastTap[k]||0)<260)keys.dash=true;lastTap[k]=performance.now();keys[k]=true}if(['j','k','u','i','o'].includes(k)){if(keys.j&&k==='u'||keys.u&&k==='j')keys.attack='throw';else keys.attack=k;keys[k]=true}e.preventDefault()});addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false});
$$('#touch button').forEach(b=>{let k=b.dataset.key;let down=e=>{e.preventDefault();if(['j','u','o'].includes(k))keys.attack=k;else keys[k]=true};let up=e=>{e.preventDefault();keys[k]=false};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up)});
})();
