(() => {
'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fighters=[
 {name:'REX',style:'BOXING / KICKBOXING',power:91,speed:72,defense:88,skin:'#b86e4d',gear:'#16171a',tone:'#92352b',accent:'#e1332f',portrait:'ChatGPT%20Image%20Aug%2031%2C%202026%2C%2012_45_44%20AM.png'},
 {name:'KAI',style:'MUAY THAI',power:78,speed:94,defense:72,skin:'#b8744f',gear:'#6e1718',tone:'#9a5526',accent:'#e8ad42'},
 {name:'ARJUN',style:'MIXED MARTIAL ARTS',power:84,speed:84,defense:82,skin:'#845238',gear:'#183c3d',tone:'#29645e',accent:'#41a897'}
];
const attacks={
 j:{name:'Jab',wind:5,active:5,recovery:11,damage:6,range:80,cost:7,type:'high'},
 k:{name:'Heavy Cross',wind:14,active:6,recovery:22,damage:14,range:92,cost:18,type:'high',heavy:true},
 u:{name:'Low Kick',wind:9,active:6,recovery:16,damage:8,range:105,cost:11,type:'low'},
 i:{name:'Roundhouse',wind:17,active:7,recovery:25,damage:17,range:130,cost:23,type:'high',heavy:true,knock:true},
 o:{name:'Beast Rush',wind:20,active:10,recovery:31,damage:25,range:145,cost:10,special:50,type:'mid',heavy:true,knock:true},
 throw:{name:'Throw',wind:10,active:5,recovery:25,damage:16,range:52,cost:20,type:'throw',knock:true},
 jump:{name:'Flying Strike',wind:5,active:10,recovery:20,damage:12,range:105,cost:14,type:'mid',heavy:true}
};
// Text-only crop data keeps the PR binary-free. At runtime these rectangles are
// cut from the supplied (already repository-owned) sheet into transparent canvases.
const rexFrameRects={
 idle:[[257,34,73,154],[325,34,77,154],[397,34,78,154],[467,34,77,154],[535,34,76,154],[606,34,75,154]],
 guard:[[690,39,80,150],[759,39,80,150],[824,39,82,150],[892,39,81,150]],
 'walk-forward':[[971,38,84,151],[1037,38,82,151],[1102,38,83,151],[1165,38,83,151],[1230,38,72,151]],
 'walk-backward':[[257,210,93,147],[343,210,88,147],[427,210,91,147],[513,210,88,147],[596,210,87,147]],
 jump:[[684,205,91,151],[758,199,90,157],[829,199,89,157],[902,205,85,151]],
 crouch:[[984,215,92,142],[1060,215,91,142],[1137,215,94,142],[1213,215,84,142]],
 'light-punch':[[253,374,95,147],[333,374,95,147],[414,374,91,147],[494,374,96,147],[574,374,95,147]],
 'heavy-punch':[[672,374,91,148],[747,374,94,148],[823,374,108,148],[908,374,114,148],[1004,374,105,148],[1089,374,104,148],[1175,374,116,148]],
 'light-kick':[[253,544,88,143],[325,544,101,143],[403,544,114,143],[495,544,103,143],[580,544,91,143]],
 'heavy-kick':[[675,544,82,143],[741,544,105,143],[821,544,114,143],[910,544,105,143],[994,544,83,143]],
 'knee-strike':[[1065,544,82,143],[1130,544,92,143],[1203,544,94,143]],
 special:[[249,707,111,121],[342,707,145,121],[467,700,167,128],[610,698,169,130],[758,698,169,130],[907,693,170,135],[1064,687,226,141]],
 hit:[[251,845,78,149],[315,845,78,149],[377,845,84,149],[443,845,92,149],[520,845,118,149]],
 knockdown:[[645,845,105,149],[728,845,103,149],[810,845,79,149]],
 recovery:[[888,845,82,149],[953,845,82,149],[1018,845,91,149]],
 victory:[[1096,833,105,166],[1182,833,111,166]]
};
const rexAnimations={},rexSheet=new Image();
function extractRexFrame(rect){
 const [sx,sy,w,h]=rect,c=document.createElement('canvas'),cx=c.getContext('2d',{willReadFrequently:true});c.width=w;c.height=h;cx.drawImage(rexSheet,sx,sy,w,h,0,0,w,h);
 const frame=cx.getImageData(0,0,w,h),p=frame.data,corner=[[0,0],[w-1,0],[0,h-1],[w-1,h-1]].map(([x,y])=>[p[(y*w+x)*4],p[(y*w+x)*4+1],p[(y*w+x)*4+2]]);
 for(let y=0;y<h;y++)for(let x=0;x<w;x++){let i=(y*w+x)*4,tx=x/Math.max(1,w-1),ty=y/Math.max(1,h-1),distance=0;for(let channel=0;channel<3;channel++){let top=corner[0][channel]*(1-tx)+corner[1][channel]*tx,bottom=corner[2][channel]*(1-tx)+corner[3][channel]*tx,delta=p[i+channel]-(top*(1-ty)+bottom*ty);distance+=delta*delta}if(distance<42*42)p[i+3]=0;else if(distance<55*55)p[i+3]=Math.min(p[i+3],Math.round((Math.sqrt(distance)-42)/13*255))}
 cx.putImageData(frame,0,0);return c
}
rexSheet.onload=()=>{for(const [state,rects] of Object.entries(rexFrameRects))rexAnimations[state]=rects.map(extractRexFrame)};
rexSheet.src='ChatGPT%20Image%20Aug%2031%2C%202026%2C%2012_45_44%20AM.png';
let selected=0,mode='menu',difficulty='Normal',last=0,paused=false,round=1,time=90,roundClock=0,roundWins=[0,0],shake=0,zoom=1,slow=1,hitFreeze=0,particles=[],keys={},lastTap={},sound=true,audio=null,announceTimer=0,aiClock=0;

class FighterAnimation{
 constructor(owner){this.owner=owner;this.state='idle';this.previous='idle';this.time=0;this.blend=1;this.recoil=0;this.step=0}
 set(state){state=({'walk':'walk-forward','back':'walk-backward','dash':'walk-forward','crouchguard':'crouch','jab':'light-punch','heavy-cross':'heavy-punch','low-kick':'light-kick','roundhouse':'heavy-kick','flying-strike':'knee-strike','throw':'knee-strike','beast-rush':'special'}[state]||state);if(state===this.state)return;this.previous=this.state;this.state=state;this.time=0;this.blend=0}
 update(dt){this.time+=dt;this.blend=Math.min(1,this.blend+dt*11);this.recoil*=Math.pow(.015,dt);if(['walk-forward','walk-backward','dash'].includes(this.state))this.step+=dt*(this.state==='dash'?14:8);else this.step+=(0-this.step)*Math.min(1,dt*5)}
 attackPhase(){let f=this.owner,a=this.owner.attack;if(!a)return 0;return f.frame<a.wind?f.frame/a.wind:f.frame<a.wind+a.active?1+(f.frame-a.wind)/a.active:2+(f.frame-a.wind-a.active)/a.recovery}
}
function fit(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)} addEventListener('resize',fit);fit();
function cards(){ $('#fighterCards').innerHTML=fighters.map((f,i)=>`<article class="fighter-card ${i===selected?'selected':''}" data-i="${i}"><div class="portrait ${f.portrait?'portrait-art':''}" style="--skin:${f.skin};--gear:${f.gear};--tone:${f.tone}${f.portrait?`;--portrait:url('${f.portrait}')`:''}"><i class="head"></i><i class="body"></i></div><div class="fighter-data"><span>${f.style}</span><h3>${f.name}</h3>${['POWER','SPEED','DEFENSE'].map(x=>`<div class="stat"><span>${x}</span><i style="--v:${f[x.toLowerCase()]}%"></i></div>`).join('')}</div></article>`).join(''); $$('.fighter-card').forEach(c=>c.onclick=()=>{selected=+c.dataset.i;cards();tone(180,.05)}) }cards();
function screen(id){$$('.screen').forEach(x=>x.classList.remove('active')); if(id)$('#'+id).classList.add('active');mode=id||'fight'}
$$('.back').forEach(b=>b.onclick=()=>screen('menu'));$('#selectBtn').onclick=()=>screen('select');$('#howBtn').onclick=()=>screen('how');$('#playBtn').onclick=()=>{screen('select')};$('#beginBtn').onclick=()=>{difficulty=$('#difficulty').value;startMatch()};
function mainMenu(){paused=false;$('#pause').classList.add('hidden');$('#gameover').classList.add('hidden');$('#hud').classList.add('hidden');$('#touch').classList.add('hidden');screen('menu')}
$$('.main-menu').forEach(b=>b.onclick=mainMenu);$('#pauseBtn').onclick=()=>togglePause(true);$('#resumeBtn').onclick=()=>togglePause(false);$('#restartBtn').onclick=startMatch;$('#againBtn').onclick=startMatch;
$$('.sound-btn').forEach(b=>b.onclick=()=>{sound=!sound;$$('.sound-btn').forEach(x=>x.textContent=(sound?'◖ SOUND ON':'◖ SOUND OFF'))});
function togglePause(v){if(mode!=='fight')return;paused=v;$('#pause').classList.toggle('hidden',!v)}
function tone(freq,dur=.08,type='sine',vol=.12){if(!sound)return; audio ||= new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(40,freq*.35),audio.currentTime+dur);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
class Fighter{
 constructor(data,side){this.data=data;this.side=side;this.animation=new FighterAnimation(this);this.reset()}
 reset(){this.x=this.side?innerWidth*.73:innerWidth*.27;this.y=0;this.vx=0;this.vy=0;this.health=100;this.stamina=100;this.meter=0;this.state='idle';this.frame=0;this.attack=null;this.hit=false;this.facing=this.side?-1:1;this.combo=[];this.comboTime=0;this.stun=0;this.knock=0;this.flash=0;this.guardTime=0;this.victory=false;this.animation.set('idle')}
 act(key){if(this.stun||this.knock||this.attack||this.state==='jump')return; if(key==='o'&&this.meter<50)return;let a=attacks[key];if(!a)return;if(this.stamina<a.cost)return;this.stamina-=a.cost;if(a.special)this.meter-=a.special;this.attack={...a,key};this.frame=0;this.hit=false;this.state='attack';this.combo.push(key);this.combo=this.combo.slice(-3);this.comboTime=55;tone(a.heavy?105:170,.08,'sawtooth',.06)}
 update(input,foe){this.facing=foe.x>this.x?1:-1;this.flash=Math.max(0,this.flash-1);this.guardTime=Math.max(0,this.guardTime-1);if(this.comboTime>0)this.comboTime--;else this.combo=[];
  if(this.victory){this.state='victory';this.animation.set('victory');this.animation.update(1/60);return}
  if(this.knock){this.knock--;this.state=this.knock>25?'knockdown':'recovery';this.animation.set(this.state);this.animation.update(1/60);return}if(this.stun){this.stun--;this.state='hit';this.animation.set('hit');this.animation.update(1/60);return}
  if(this.attack){this.frame++;let a=this.attack;if(this.frame>=a.wind&&this.frame<a.wind+a.active&&!this.hit&&Math.abs(foe.x-this.x)<a.range+(this.state==='jump'?20:0)){this.hit=true;hit(this,foe,a)}if(this.frame>=a.wind+a.active+a.recovery){this.attack=null;this.state='idle'}this.animation.set(this.attack?(this.attack.key==='o'?'special':this.attack.name.toLowerCase().replaceAll(' ','-')):'idle');this.animation.update(1/60);return}
  if(this.state==='jump'){this.vy+=.8;this.y+=this.vy;if(input.attack)this.act('jump');if(this.y>=0){this.y=0;this.vy=0;this.state='idle';dust(this.x,ground(),8)}this.x+=this.vx;this.animation.set('jump');this.animation.update(1/60);return}
  const guarding=input.l, crouch=input.s; if(guarding){this.state=crouch?'crouchguard':'guard';this.vx*=.72;this.guardTime=Math.min(10,this.guardTime+2)}else if(crouch){this.state='crouch';this.vx*=.65}else{let dir=(input.d?1:0)-(input.a?1:0);let speed=this.stamina<20?2.3:3.4;if(input.dash&&this.stamina>=12){this.vx=dir*10;this.stamina-=12;this.state='dash'}else{this.vx+=(dir*speed-this.vx)*.24;this.state=Math.abs(this.vx)>.4?(this.vx*this.facing>0?'walk':'back'):'idle'}if(input.w){this.state='jump';this.vy=-13;this.vx+=dir*2;tone(100,.05)}if(input.attack)this.act(input.attack)}
  this.x+=this.vx;this.x=Math.max(65,Math.min(innerWidth-65,this.x));this.stamina=Math.min(100,this.stamina+(.23*(this.state==='idle'?1.5:1)));this.meter=Math.min(100,this.meter+.018);this.animation.set(this.attack?(this.attack.key==='o'?'special':this.attack.name.toLowerCase().replaceAll(' ','-')):this.state);this.animation.update(1/60)}
}
let player,cpu;
function hit(at,def,a){let blocking=(def.state==='guard'&&a.type!=='low')||(def.state==='crouchguard'&&a.type!=='high');if(a.type==='throw')blocking=false;let counter=!!def.attack&&def.frame<def.attack.wind;let critical=Math.random()<.08;let dmg=a.damage*(counter?1.3:1)*(critical?1.35:1);hitFreeze=a.heavy?7:4;def.animation.recoil=a.heavy?1:.55;if(blocking){dmg*=.18;def.stamina-=a.damage*1.25;def.stun=5;tone(320,.07,'square');spark(def.x,ground()+def.y-135,'#d7d1bf',8);if(def.stamina<=0){def.stamina=0;def.stun=25;dmg*=2.5}}else{def.health=Math.max(0,def.health-dmg);def.stun=a.heavy?18:10;def.vx=at.facing*(a.heavy?11:4);at.meter=Math.min(100,at.meter+dmg*1.2);def.meter=Math.min(100,def.meter+dmg*.7);shake=a.heavy?16:6;slow=a.heavy?.38:.75;setTimeout(()=>slow=1,a.heavy?100:40);tone(a.heavy?55:90,a.heavy?.18:.09,'sawtooth',.18);spark(def.x+at.facing*15,ground()+def.y-145,critical?'#fff1a6':'#ef493e',a.heavy?24:12);dust(def.x,ground(),a.heavy?12:6);if(a.knock||def.health<=0){def.knock=def.health<=0?150:48;def.stun=0}if(at.side===0){let n=at.combo.length;$('#combo').innerHTML=n>1?`${n} HIT <small>COMBO</small>`:''}if(counter)flashText('COUNTER');if(critical)flashText('CRITICAL')}
 if(def.health<=0)endRound(at)}
function spark(x,y,color,n){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*12,vy:(Math.random()-.7)*10,life:25+Math.random()*15,color,size:2+Math.random()*5})}
function dust(x,y,n){for(let i=0;i<n;i++)particles.push({x:x+(Math.random()-.5)*45,y:y-Math.random()*8,vx:(Math.random()-.5)*3,vy:-Math.random()*2,life:30+Math.random()*25,color:'#a8a098',size:7+Math.random()*15,dust:true})}
function flashText(t){$('#combo').innerHTML=t}
function ground(){return innerHeight*.82}
function startMatch(){screen(null);$('#pause,#gameover').addClass?.('hidden');$('#pause').addClass?.('hidden');$('#gameover').classList.add('hidden');$('#hud').classList.remove('hidden');if(matchMedia('(pointer:coarse)').matches)$('#touch').classList.remove('hidden');roundWins=[0,0];round=1;player=new Fighter(fighters[selected],0);let ci=(selected+1+Math.floor(Math.random()*2))%3;cpu=new Fighter(fighters[ci],1);$('#pName').textContent=player.data.name;$('#cName').textContent=cpu.data.name;beginRound()}
function beginRound(){time=90;roundClock=0;player.reset();cpu.reset();paused=false;announce(round===3?'FINAL ROUND':`ROUND ${round}`,800,()=>announce('FIGHT',650));tone(440,.3,'square',.08)}
function announce(t,ms=700,cb){$('#announcement').textContent=t;announceTimer=ms;setTimeout(()=>{if($('#announcement').textContent===t)$('#announcement').textContent='';cb&&cb()},ms)}
function endRound(winner){if(roundClock<0)return;roundClock=-999;let wi=winner.side;roundWins[wi]++;winner.victory=true;winner.animation.set('victory');announce('KO',1300,()=>{if(roundWins[wi]>=2){$('#winner').textContent=winner.data.name+' WINS';$('#score').textContent=`ROUNDS ${roundWins[wi]} — ${roundWins[1-wi]}`;$('#gameover').classList.remove('hidden');tone(48,.8,'sawtooth',.2)}else{round++;beginRound()}});slow=.16;zoom=1.1;shake=20;setTimeout(()=>{slow=1;zoom=1},850)}
function aiInput(){let d=Math.abs(player.x-cpu.x),out={};let cfg=difficulty==='Easy'?{react:24,block:.13,attack:.42}:difficulty==='Hard'?{react:7,block:.42,attack:.76}:{react:14,block:.27,attack:.59};aiClock--;if(aiClock<=0){aiClock=cfg.react+Math.random()*cfg.react;let r=Math.random();if(player.attack&&r<cfg.block){cpu.aiGuard=18+Math.random()*18}else if(d>145)cpu.aiMove='a';else if(d<68)cpu.aiMove=Math.random()<.5?'d':null;else cpu.aiMove=null;if(d<150&&Math.random()<cfg.attack){let choices=['j','u','k','i'];if(cpu.meter>=50&&Math.random()<.22)choices.push('o');let last=cpu.combo.at(-1),filtered=choices.filter(x=>x!==last);cpu.aiAttack=filtered[Math.floor(Math.random()*filtered.length)]}}
 if(cpu.aiGuard>0){cpu.aiGuard--;out.l=true;out.s=player.attack?.type==='low'}else{out[cpu.aiMove]=true;if(cpu.aiAttack){out.attack=cpu.aiAttack;cpu.aiAttack=null}}return out}
function update(dt){if(mode!=='fight'||paused||roundClock<0)return;if(hitFreeze>0){hitFreeze--;return}roundClock+=dt;if(roundClock<1.5)return;time=Math.max(0,time-dt);if(time===0){endRound(player.health>=cpu.health?player:cpu);return}let inp={a:keys.a,d:keys.d,w:keys.w,s:keys.s,l:keys.l,dash:keys.dash,attack:keys.attack};keys.attack=null;keys.dash=false;player.update(inp,cpu);cpu.update(aiInput(),player);if(Math.abs(player.x-cpu.x)<72){let push=(72-Math.abs(player.x-cpu.x))*.08;player.x-=player.facing*push;cpu.x+=player.facing*push}particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=p.dust?.05:.4;p.life--});particles=particles.filter(p=>p.life>0).slice(-160);updateHud()}
function updateHud(){for(const [id,v] of [['pHealth',player.health],['pStamina',player.stamina],['pSpecial',player.meter],['cHealth',cpu.health],['cStamina',cpu.stamina],['cSpecial',cpu.meter]])$('#'+id).style.width=Math.max(0,v)+'%';$('#timer').textContent=Math.ceil(time);$('#roundNo').textContent=round;$('#roundPips').textContent=`${'◆'.repeat(roundWins[0])}${'◇'.repeat(2-roundWins[0])}  ${'◆'.repeat(roundWins[1])}${'◇'.repeat(2-roundWins[1])}`}
function drawArena(t){let w=innerWidth,h=innerHeight,g=ground(),pulse=.5+.5*Math.sin(t*.0013);let grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#030405');grad.addColorStop(.54,'#24201f');grad.addColorStop(1,'#070708');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.save();ctx.translate(Math.sin(t*.00018)*12,0);ctx.fillStyle='#121315';for(let y=25;y<g-130;y+=64)for(let x=(y/64%2)*48-80;x<w+100;x+=96){ctx.fillRect(x,y,94,62);ctx.strokeStyle='#242426';ctx.strokeRect(x,y,94,62)}ctx.restore();for(let i=0;i<4;i++){let x=w*(.14+i*.25)+Math.sin(t*.0007+i)*18,beam=ctx.createLinearGradient(x,0,x,g);beam.addColorStop(0,`rgba(255,225,190,${.1+pulse*.04})`);beam.addColorStop(1,'transparent');ctx.fillStyle=beam;ctx.beginPath();ctx.moveTo(x-22,0);ctx.lineTo(x+22,0);ctx.lineTo(x+180,g);ctx.lineTo(x-180,g);ctx.fill();ctx.fillStyle='#f0d3b0';ctx.globalAlpha=.45;ctx.fillRect(x-25,0,50,5);ctx.globalAlpha=1}for(let i=0;i<8;i++){let x=(i*233+t*.012)% (w+300)-150,y=90+(i%4)*82,r=95+(i%3)*35;let fog=ctx.createRadialGradient(x,y,0,x,y,r);fog.addColorStop(0,'#c4b7aa0b');fog.addColorStop(1,'transparent');ctx.fillStyle=fog;ctx.fillRect(x-r,y-r,r*2,r*2)}ctx.fillStyle='#090909';for(let i=0;i<28;i++){let x=i*w/27+Math.sin(t*.001+i*2)*7,y=g-118-(i%4)*9;ctx.beginPath();ctx.arc(x,y,14+(i%3)*3,0,7);ctx.fill();ctx.fillRect(x-16,y+8,32,74);if(i%5===0){ctx.strokeStyle='#171313';ctx.lineWidth=8;ctx.beginPath();ctx.moveTo(x,y+25);ctx.lineTo(x+Math.sin(t*.004+i)*18,y-5);ctx.stroke()}}ctx.strokeStyle='#5b5550';ctx.lineWidth=7;ctx.beginPath();ctx.moveTo(0,g-72);ctx.lineTo(w,g-72);ctx.stroke();ctx.lineWidth=1;ctx.strokeStyle='#55505a55';for(let x=-30;x<w;x+=48){ctx.beginPath();ctx.moveTo(x,g-72);ctx.lineTo(x+25,g);ctx.stroke()}let floor=ctx.createLinearGradient(0,g-75,0,h);floor.addColorStop(0,'#3a3532');floor.addColorStop(.2,'#171616');floor.addColorStop(1,'#050505');ctx.fillStyle=floor;ctx.fillRect(0,g-75,w,h-g+75);ctx.strokeStyle='#ffffff0c';for(let x=-100;x<w+100;x+=135){ctx.beginPath();ctx.moveTo(w/2+(x-w/2)*.5,g-75);ctx.lineTo(x,h);ctx.stroke()}ctx.fillStyle='#d0b39812';ctx.fillRect(0,g-2,w,3)}
function drawSimpleFighter(f){let x=f.x,y=ground()+f.y,face=f.facing,d=f.data;ctx.save();ctx.translate(x,y);ctx.scale(face,1);if(f.knock>25){ctx.rotate(-1.35);ctx.translate(0,-30)}let bob=f.state==='idle'?Math.sin(performance.now()*.007)*3:0,crouch=f.state.includes('crouch')?38:0;ctx.translate(0,bob+crouch);let attacking=f.attack,prog=attacking?f.frame/(attacking.wind+attacking.active+attacking.recovery):0;let punch=attacking&&['j','k','o'].includes(attacking.key)?Math.sin(Math.min(1,prog*2.2)*Math.PI)*55:0,kick=attacking&&['u','i','jump'].includes(attacking.key)?Math.sin(Math.min(1,prog*2)*Math.PI):0,guard=f.state.includes('guard');ctx.strokeStyle=d.skin;ctx.lineCap='round';ctx.lineWidth=20;ctx.beginPath();ctx.moveTo(-24,-98);ctx.lineTo(-29+kick*32,-45);ctx.lineTo(-36-kick*52,0);ctx.stroke();ctx.beginPath();ctx.moveTo(22,-98);ctx.lineTo(30+kick*70,-58-kick*40);ctx.lineTo(35+kick*110,-12-kick*60);ctx.stroke();ctx.fillStyle='#17191b';ctx.fillRect(-47,-96,91,25);ctx.strokeStyle=d.skin;ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(-38,-172);ctx.lineTo(-55,-125);ctx.lineTo(guard?8:-42,-92);ctx.stroke();ctx.beginPath();ctx.moveTo(35,-173);ctx.lineTo(guard?18:48+punch,-132-(punch*.3));ctx.lineTo(guard?5:54+punch,-107-(punch*.25));ctx.stroke();ctx.fillStyle=d.accent;ctx.beginPath();ctx.roundRect(guard?-3:43+punch,-120-(punch*.25),25,20,7);ctx.fill();ctx.fillStyle=d.gear;ctx.beginPath();ctx.moveTo(-42,-178);ctx.quadraticCurveTo(0,-205,42,-178);ctx.lineTo(34,-90);ctx.lineTo(-34,-90);ctx.closePath();ctx.fill();ctx.fillStyle=d.skin;ctx.beginPath();ctx.ellipse(0,-215,31,39,0,0,7);ctx.fill();ctx.fillStyle='#171513';ctx.beginPath();ctx.arc(0,-231,31,Math.PI,0);ctx.fill();ctx.restore()}

function drawRex(f){
 let state=f.animation.state,frames=rexAnimations[state]||rexAnimations.idle,index;if(!frames)return;
 if(f.attack){let total=f.attack.wind+f.attack.active+f.attack.recovery;index=Math.min(frames.length-1,Math.floor((f.frame/total)*frames.length))}
 else if(['hit','knockdown','recovery'].includes(state))index=Math.min(frames.length-1,Math.floor(f.animation.time*12));
 else if(state==='jump')index=Math.min(frames.length-1,Math.floor(Math.max(0,Math.min(1,(-f.y)/55))*frames.length));
 else index=Math.floor(f.animation.time*(state==='idle'?6:state==='victory'?3:10))%frames.length;
 let image=frames[index]||frames[0];if(!image?.width)return;
 const scale=2.05,w=image.width*scale,h=image.height*scale;
 ctx.save();ctx.translate(f.x,ground()+f.y);ctx.scale(f.facing,1);ctx.imageSmoothingEnabled=true;ctx.drawImage(image,-w/2,-h,w,h);ctx.restore()
}
function render(t){let w=innerWidth,h=innerHeight;ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.translate(w/2,h/2);ctx.scale(zoom,zoom);ctx.translate(-w/2,-h/2);drawArena(t);if(player){player.data.name==='REX'?drawRex(player,t):drawSimpleFighter(player);cpu.data.name==='REX'?drawRex(cpu,t):drawSimpleFighter(cpu)}particles.forEach(p=>{ctx.globalAlpha=Math.min(1,p.life/25)*(p.dust?.28:1);ctx.fillStyle=p.color;if(p.dust){ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,7);ctx.fill()}else ctx.fillRect(p.x,p.y,p.size,p.size)});ctx.restore();ctx.globalAlpha=1;shake*=.82}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt*slow);render(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(k==='escape')togglePause(!paused);if(['a','d','w','s','l'].includes(k)){if(!e.repeat&&['a','d'].includes(k)&&performance.now()-(lastTap[k]||0)<260)keys.dash=true;lastTap[k]=performance.now();keys[k]=true}if(['j','k','u','i','o'].includes(k)){if(keys.j&&k==='u'||keys.u&&k==='j')keys.attack='throw';else keys.attack=k;keys[k]=true}e.preventDefault()});addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false});
$$('#touch button').forEach(b=>{let k=b.dataset.key;let down=e=>{e.preventDefault();if(['j','u','o'].includes(k))keys.attack=k;else keys[k]=true};let up=e=>{e.preventDefault();keys[k]=false};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up)});
})();
