(() => {
'use strict';
const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d');
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const fighters=[
 {name:'REX',style:'BOXING / KICKBOXING',power:91,speed:72,defense:88,skin:'#9a5c3f',gear:'#26282a',tone:'#92352b',accent:'#e1332f'},
 {name:'KAI',style:'MUAY THAI',power:78,speed:94,defense:72,skin:'#b8744f',gear:'#6e1718',tone:'#9a5526',accent:'#e8ad42'},
 {name:'ARJUN',style:'MIXED MARTIAL ARTS',power:84,speed:84,defense:82,skin:'#845238',gear:'#183c3d',tone:'#29645e',accent:'#41a897'}
];
const attacks={
 j:{name:'Jab',wind:5,active:5,recovery:11,damage:6,range:80,cost:7,type:'high'},
 k:{name:'Heavy Cross',wind:14,active:6,recovery:22,damage:14,range:92,cost:18,type:'high',heavy:true},
 u:{name:'Low Kick',wind:9,active:6,recovery:16,damage:8,range:105,cost:11,type:'low'},
 i:{name:'Roundhouse',wind:17,active:7,recovery:25,damage:17,range:130,cost:23,type:'high',heavy:true,knock:true},
 o:{name:'Signature',wind:20,active:10,recovery:31,damage:25,range:145,cost:10,special:50,type:'mid',heavy:true,knock:true},
 throw:{name:'Throw',wind:10,active:5,recovery:25,damage:16,range:52,cost:20,type:'throw',knock:true},
 jump:{name:'Flying Strike',wind:5,active:10,recovery:20,damage:12,range:105,cost:14,type:'mid',heavy:true}
};
let selected=0,mode='menu',difficulty='Normal',last=0,paused=false,round=1,time=90,roundClock=0,roundWins=[0,0],shake=0,zoom=1,slow=1,particles=[],keys={},lastTap={},sound=true,audio=null,announceTimer=0,aiClock=0;
function fit(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);canvas.width=r.width*d;canvas.height=r.height*d;ctx.setTransform(d,0,0,d,0,0)} addEventListener('resize',fit);fit();
function cards(){ $('#fighterCards').innerHTML=fighters.map((f,i)=>`<article class="fighter-card ${i===selected?'selected':''}" data-i="${i}"><div class="portrait" style="--skin:${f.skin};--gear:${f.gear};--tone:${f.tone}"><i class="head"></i><i class="body"></i></div><div class="fighter-data"><span>${f.style}</span><h3>${f.name}</h3>${['POWER','SPEED','DEFENSE'].map(x=>`<div class="stat"><span>${x}</span><i style="--v:${f[x.toLowerCase()]}%"></i></div>`).join('')}</div></article>`).join(''); $$('.fighter-card').forEach(c=>c.onclick=()=>{selected=+c.dataset.i;cards();tone(180,.05)}) }cards();
function screen(id){$$('.screen').forEach(x=>x.classList.remove('active')); if(id)$('#'+id).classList.add('active');mode=id||'fight'}
$$('.back').forEach(b=>b.onclick=()=>screen('menu'));$('#selectBtn').onclick=()=>screen('select');$('#howBtn').onclick=()=>screen('how');$('#playBtn').onclick=()=>{screen('select')};$('#beginBtn').onclick=()=>{difficulty=$('#difficulty').value;startMatch()};
function mainMenu(){paused=false;$('#pause').classList.add('hidden');$('#gameover').classList.add('hidden');$('#hud').classList.add('hidden');$('#touch').classList.add('hidden');screen('menu')}
$$('.main-menu').forEach(b=>b.onclick=mainMenu);$('#pauseBtn').onclick=()=>togglePause(true);$('#resumeBtn').onclick=()=>togglePause(false);$('#restartBtn').onclick=startMatch;$('#againBtn').onclick=startMatch;
$$('.sound-btn').forEach(b=>b.onclick=()=>{sound=!sound;$$('.sound-btn').forEach(x=>x.textContent=(sound?'◖ SOUND ON':'◖ SOUND OFF'))});
function togglePause(v){if(mode!=='fight')return;paused=v;$('#pause').classList.toggle('hidden',!v)}
function tone(freq,dur=.08,type='sine',vol=.12){if(!sound)return; audio ||= new (window.AudioContext||window.webkitAudioContext)();const o=audio.createOscillator(),g=audio.createGain();o.type=type;o.frequency.setValueAtTime(freq,audio.currentTime);o.frequency.exponentialRampToValueAtTime(Math.max(40,freq*.35),audio.currentTime+dur);g.gain.setValueAtTime(vol,audio.currentTime);g.gain.exponentialRampToValueAtTime(.001,audio.currentTime+dur);o.connect(g).connect(audio.destination);o.start();o.stop(audio.currentTime+dur)}
class Fighter{
 constructor(data,side){this.data=data;this.side=side;this.reset()}
 reset(){this.x=this.side?innerWidth*.73:innerWidth*.27;this.y=0;this.vx=0;this.vy=0;this.health=100;this.stamina=100;this.meter=0;this.state='idle';this.frame=0;this.attack=null;this.hit=false;this.facing=this.side?-1:1;this.combo=[];this.comboTime=0;this.stun=0;this.knock=0;this.flash=0;this.guardTime=0}
 act(key){if(this.stun||this.knock||this.attack||this.state==='jump')return; if(key==='o'&&this.meter<50)return;let a=attacks[key];if(!a)return;if(this.stamina<a.cost)return;this.stamina-=a.cost;if(a.special)this.meter-=a.special;this.attack={...a,key};this.frame=0;this.hit=false;this.state='attack';this.combo.push(key);this.combo=this.combo.slice(-3);this.comboTime=55;tone(a.heavy?105:170,.08,'sawtooth',.06)}
 update(input,foe){this.facing=foe.x>this.x?1:-1;this.flash=Math.max(0,this.flash-1);this.guardTime=Math.max(0,this.guardTime-1);if(this.comboTime>0)this.comboTime--;else this.combo=[];
  if(this.knock){this.knock--;this.state=this.knock>25?'knockdown':'recovery';return}if(this.stun){this.stun--;this.state='hit';return}
  if(this.attack){this.frame++;let a=this.attack;if(this.frame>=a.wind&&this.frame<a.wind+a.active&&!this.hit&&Math.abs(foe.x-this.x)<a.range+(this.state==='jump'?20:0)){this.hit=true;hit(this,foe,a)}if(this.frame>=a.wind+a.active+a.recovery){this.attack=null;this.state='idle'}return}
  if(this.state==='jump'){this.vy+=.8;this.y+=this.vy;if(input.attack)this.act('jump');if(this.y>=0){this.y=0;this.vy=0;this.state='idle'}this.x+=this.vx;return}
  const guarding=input.l, crouch=input.s; if(guarding){this.state=crouch?'crouchguard':'guard';this.vx*=.72;this.guardTime=Math.min(10,this.guardTime+2)}else if(crouch){this.state='crouch';this.vx*=.65}else{let dir=(input.d?1:0)-(input.a?1:0);let speed=this.stamina<20?2.3:3.4;if(input.dash&&this.stamina>=12){this.vx=dir*10;this.stamina-=12;this.state='dash'}else{this.vx+=(dir*speed-this.vx)*.24;this.state=Math.abs(this.vx)>.4?(this.vx*this.facing>0?'walk':'back'):'idle'}if(input.w){this.state='jump';this.vy=-13;this.vx+=dir*2;tone(100,.05)}if(input.attack)this.act(input.attack)}
  this.x+=this.vx;this.x=Math.max(65,Math.min(innerWidth-65,this.x));this.stamina=Math.min(100,this.stamina+(.23*(this.state==='idle'?1.5:1)));this.meter=Math.min(100,this.meter+.018)}
}
let player,cpu;
function hit(at,def,a){let blocking=(def.state==='guard'&&a.type!=='low')||(def.state==='crouchguard'&&a.type!=='high');if(a.type==='throw')blocking=false;let counter=!!def.attack&&def.frame<def.attack.wind;let critical=Math.random()<.08;let dmg=a.damage*(counter?1.3:1)*(critical?1.35:1);if(blocking){dmg*=.18;def.stamina-=a.damage*1.25;def.stun=5;tone(320,.07,'square');spark(def.x,ground()+def.y-135,'#d7d1bf',8);if(def.stamina<=0){def.stamina=0;def.stun=25;dmg*=2.5}}else{def.health=Math.max(0,def.health-dmg);def.stun=a.heavy?18:10;def.vx=at.facing*(a.heavy?8:3);at.meter=Math.min(100,at.meter+dmg*1.2);def.meter=Math.min(100,def.meter+dmg*.7);shake=a.heavy?12:5;slow=a.heavy?.38:.75;setTimeout(()=>slow=1,a.heavy?100:40);tone(a.heavy?55:90,a.heavy?.18:.09,'sawtooth',.18);spark(def.x+at.facing*15,ground()+def.y-145,critical?'#fff1a6':'#ef493e',a.heavy?18:10);if(a.knock||def.health<=0){def.knock=def.health<=0?150:48;def.stun=0}if(at.side===0){let n=at.combo.length;$('#combo').innerHTML=n>1?`${n} HIT <small>COMBO</small>`:''}if(counter)flashText('COUNTER');if(critical)flashText('CRITICAL')}
 if(def.health<=0)endRound(at)}
function spark(x,y,color,n){for(let i=0;i<n;i++)particles.push({x,y,vx:(Math.random()-.5)*12,vy:(Math.random()-.7)*10,life:25+Math.random()*15,color,size:2+Math.random()*5})}
function flashText(t){$('#combo').innerHTML=t}
function ground(){return innerHeight*.82}
function startMatch(){screen(null);$('#pause,#gameover').addClass?.('hidden');$('#pause').addClass?.('hidden');$('#gameover').classList.add('hidden');$('#hud').classList.remove('hidden');if(matchMedia('(pointer:coarse)').matches)$('#touch').classList.remove('hidden');roundWins=[0,0];round=1;player=new Fighter(fighters[selected],0);let ci=(selected+1+Math.floor(Math.random()*2))%3;cpu=new Fighter(fighters[ci],1);$('#pName').textContent=player.data.name;$('#cName').textContent=cpu.data.name;beginRound()}
function beginRound(){time=90;roundClock=0;player.reset();cpu.reset();paused=false;announce(round===3?'FINAL ROUND':`ROUND ${round}`,800,()=>announce('FIGHT',650));tone(440,.3,'square',.08)}
function announce(t,ms=700,cb){$('#announcement').textContent=t;announceTimer=ms;setTimeout(()=>{if($('#announcement').textContent===t)$('#announcement').textContent='';cb&&cb()},ms)}
function endRound(winner){if(roundClock<0)return;roundClock=-999;let wi=winner.side;roundWins[wi]++;announce('KO',1300,()=>{if(roundWins[wi]>=2){$('#winner').textContent=winner.data.name+' WINS';$('#score').textContent=`ROUNDS ${roundWins[wi]} — ${roundWins[1-wi]}`;$('#gameover').classList.remove('hidden');tone(48,.8,'sawtooth',.2)}else{round++;beginRound()}});slow=.2;zoom=1.08;setTimeout(()=>{slow=1;zoom=1},700)}
function aiInput(){let d=Math.abs(player.x-cpu.x),out={};let cfg=difficulty==='Easy'?{react:24,block:.13,attack:.42}:difficulty==='Hard'?{react:7,block:.42,attack:.76}:{react:14,block:.27,attack:.59};aiClock--;if(aiClock<=0){aiClock=cfg.react+Math.random()*cfg.react;let r=Math.random();if(player.attack&&r<cfg.block){cpu.aiGuard=18+Math.random()*18}else if(d>145)cpu.aiMove='a';else if(d<68)cpu.aiMove=Math.random()<.5?'d':null;else cpu.aiMove=null;if(d<150&&Math.random()<cfg.attack){let choices=['j','u','k','i'];if(cpu.meter>=50&&Math.random()<.22)choices.push('o');let last=cpu.combo.at(-1),filtered=choices.filter(x=>x!==last);cpu.aiAttack=filtered[Math.floor(Math.random()*filtered.length)]}}
 if(cpu.aiGuard>0){cpu.aiGuard--;out.l=true;out.s=player.attack?.type==='low'}else{out[cpu.aiMove]=true;if(cpu.aiAttack){out.attack=cpu.aiAttack;cpu.aiAttack=null}}return out}
function update(dt){if(mode!=='fight'||paused||roundClock<0)return;roundClock+=dt;if(roundClock<1.5)return;time=Math.max(0,time-dt);if(time===0){endRound(player.health>=cpu.health?player:cpu);return}let inp={a:keys.a,d:keys.d,w:keys.w,s:keys.s,l:keys.l,dash:keys.dash,attack:keys.attack};keys.attack=null;keys.dash=false;player.update(inp,cpu);cpu.update(aiInput(),player);if(Math.abs(player.x-cpu.x)<72){let push=(72-Math.abs(player.x-cpu.x))*.08;player.x-=player.facing*push;cpu.x+=player.facing*push}particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vy+=.4;p.life--});particles=particles.filter(p=>p.life>0).slice(-120);updateHud()}
function updateHud(){for(const [id,v] of [['pHealth',player.health],['pStamina',player.stamina],['pSpecial',player.meter],['cHealth',cpu.health],['cStamina',cpu.stamina],['cSpecial',cpu.meter]])$('#'+id).style.width=Math.max(0,v)+'%';$('#timer').textContent=Math.ceil(time);$('#roundNo').textContent=round;$('#roundPips').textContent=`${'◆'.repeat(roundWins[0])}${'◇'.repeat(2-roundWins[0])}  ${'◆'.repeat(roundWins[1])}${'◇'.repeat(2-roundWins[1])}`}
function drawArena(t){let w=innerWidth,h=innerHeight,g=ground(),grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,'#07090c');grad.addColorStop(.62,'#222429');grad.addColorStop(1,'#08090a');ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.fillStyle='#191b1e';for(let y=40;y<g-120;y+=85)for(let x=(y/85%2)*55-55;x<w;x+=110){ctx.fillRect(x,y,108,82);ctx.strokeStyle='#272a2d';ctx.strokeRect(x,y,108,82)}for(let i=0;i<5;i++){let x=w*(.1+i*.2),beam=ctx.createLinearGradient(x,0,x,g);beam.addColorStop(0,'#d9e0df28');beam.addColorStop(1,'transparent');ctx.fillStyle=beam;ctx.beginPath();ctx.moveTo(x-25,0);ctx.lineTo(x+25,0);ctx.lineTo(x+180,g);ctx.lineTo(x-180,g);ctx.fill()}ctx.fillStyle='#07080a';for(let i=0;i<24;i++){let x=i*w/23+Math.sin(t*.001+i)*5,y=g-115-(i%3)*10;ctx.beginPath();ctx.arc(x,y,18+(i%2)*4,0,7);ctx.fill();ctx.fillRect(x-18,y+10,36,80)}ctx.strokeStyle='#44484b';ctx.lineWidth=6;ctx.beginPath();ctx.moveTo(0,g-75);ctx.lineTo(w,g-75);ctx.stroke();ctx.lineWidth=2;ctx.strokeStyle='#1e2022';for(let x=0;x<w;x+=65){ctx.beginPath();ctx.moveTo(x,g-75);ctx.lineTo(x+30,g);ctx.stroke()}let floor=ctx.createLinearGradient(0,g-80,0,h);floor.addColorStop(0,'#353638');floor.addColorStop(.15,'#17191b');floor.addColorStop(1,'#060708');ctx.fillStyle=floor;ctx.fillRect(0,g-75,w,h-g+75);ctx.strokeStyle='#ffffff0b';for(let x=0;x<w;x+=150){ctx.beginPath();ctx.moveTo(w/2+(x-w/2)*.55,g-75);ctx.lineTo(x,h);ctx.stroke()}ctx.fillStyle='#ffffff08';ctx.fillRect(0,g-2,w,3)}
function drawFighter(f){let x=f.x,y=ground()+f.y,face=f.facing,d=f.data;ctx.save();ctx.translate(x,y);ctx.scale(face,1);if(f.knock>25){ctx.rotate(-1.35);ctx.translate(0,-30)}let bob=f.state==='idle'?Math.sin(performance.now()*.007)*3:0,crouch=f.state.includes('crouch')?38:0;ctx.translate(0,bob+crouch);let attacking=f.attack,prog=attacking?f.frame/(attacking.wind+attacking.active+attacking.recovery):0;let punch=attacking&&['j','k','o'].includes(attacking.key)?Math.sin(Math.min(1,prog*2.2)*Math.PI)*55:0,kick=attacking&&['u','i','jump'].includes(attacking.key)?Math.sin(Math.min(1,prog*2)*Math.PI):0,guard=f.state.includes('guard');if(f.flash)ctx.globalAlpha=.6;ctx.strokeStyle=d.skin;ctx.lineCap='round';ctx.lineWidth=20;ctx.beginPath();ctx.moveTo(-24,-98);ctx.lineTo(-29+kick*32,-45);ctx.lineTo(-36-kick*52,0);ctx.stroke();ctx.beginPath();ctx.moveTo(22,-98);ctx.lineTo(30+kick*70,-58-kick*40);ctx.lineTo(35+kick*110,-12-kick*60);ctx.stroke();ctx.fillStyle='#17191b';ctx.fillRect(-47,-96,91,25);ctx.strokeStyle=d.skin;ctx.lineWidth=18;ctx.beginPath();ctx.moveTo(-38,-172);ctx.lineTo(-55,-125);ctx.lineTo(guard?8:-42,-92);ctx.stroke();ctx.beginPath();ctx.moveTo(35,-173);ctx.lineTo(guard?18:48+punch,-132-(punch*.3));ctx.lineTo(guard?5:54+punch,-107-(punch*.25));ctx.stroke();ctx.fillStyle=d.accent;ctx.beginPath();ctx.roundRect(guard?-3:43+punch,-120-(punch*.25),25,20,7);ctx.fill();ctx.fillStyle=d.gear;ctx.beginPath();ctx.moveTo(-42,-178);ctx.quadraticCurveTo(0,-205,42,-178);ctx.lineTo(34,-90);ctx.lineTo(-34,-90);ctx.closePath();ctx.fill();ctx.fillStyle=d.skin;ctx.beginPath();ctx.ellipse(0,-215,31,39,0,0,7);ctx.fill();ctx.fillStyle='#171513';ctx.beginPath();ctx.arc(0,-231,31,Math.PI,0);ctx.fill();ctx.fillStyle='#111';ctx.fillRect(15,-217,8,3);ctx.restore();if(f.y===0){ctx.save();ctx.globalAlpha=.16;ctx.fillStyle=d.accent;ctx.beginPath();ctx.ellipse(x,ground()+8,55,11,0,0,7);ctx.fill();ctx.restore()}}
function render(t){let w=innerWidth,h=innerHeight;ctx.save();ctx.translate((Math.random()-.5)*shake,(Math.random()-.5)*shake);ctx.translate(w/2,h/2);ctx.scale(zoom,zoom);ctx.translate(-w/2,-h/2);drawArena(t);if(player){drawFighter(player);drawFighter(cpu)}particles.forEach(p=>{ctx.globalAlpha=p.life/35;ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)});ctx.restore();ctx.globalAlpha=1;shake*=.82}
function loop(t){let dt=Math.min(.033,(t-last)/1000||0);last=t;update(dt*slow);render(t);requestAnimationFrame(loop)}requestAnimationFrame(loop);
addEventListener('keydown',e=>{let k=e.key.toLowerCase();if(k==='escape')togglePause(!paused);if(['a','d','w','s','l'].includes(k)){if(!e.repeat&&['a','d'].includes(k)&&performance.now()-(lastTap[k]||0)<260)keys.dash=true;lastTap[k]=performance.now();keys[k]=true}if(['j','k','u','i','o'].includes(k)){if(keys.j&&k==='u'||keys.u&&k==='j')keys.attack='throw';else keys.attack=k;keys[k]=true}e.preventDefault()});addEventListener('keyup',e=>{keys[e.key.toLowerCase()]=false});
$$('#touch button').forEach(b=>{let k=b.dataset.key;let down=e=>{e.preventDefault();if(['j','u','o'].includes(k))keys.attack=k;else keys[k]=true};let up=e=>{e.preventDefault();keys[k]=false};b.addEventListener('pointerdown',down);b.addEventListener('pointerup',up);b.addEventListener('pointercancel',up)});
})();
